// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: stories.proto

package story

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoryClient is the client API for Story service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoryClient interface {
	CreateStories(ctx context.Context, in *CreateStoriesRequest, opts ...grpc.CallOption) (*CreateStoriesResponse, error)
	UpdateStories(ctx context.Context, in *UpdateStoriesReq, opts ...grpc.CallOption) (*UpdateStoriesRes, error)
	DeleteStories(ctx context.Context, in *StoryId, opts ...grpc.CallOption) (*Void, error)
	GetAllStories(ctx context.Context, in *GetAllStoriesReq, opts ...grpc.CallOption) (*GetAllStoriesRes, error)
	GetStory(ctx context.Context, in *StoryId, opts ...grpc.CallOption) (*GetStoryRes, error)
	CommentStory(ctx context.Context, in *CommentStoryReq, opts ...grpc.CallOption) (*CommentStoryRes, error)
	GetCommentsOfStory(ctx context.Context, in *GetCommentsOfStoryReq, opts ...grpc.CallOption) (*GetCommentsOfStoryRes, error)
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error)
}

type storyClient struct {
	cc grpc.ClientConnInterface
}

func NewStoryClient(cc grpc.ClientConnInterface) StoryClient {
	return &storyClient{cc}
}

func (c *storyClient) CreateStories(ctx context.Context, in *CreateStoriesRequest, opts ...grpc.CallOption) (*CreateStoriesResponse, error) {
	out := new(CreateStoriesResponse)
	err := c.cc.Invoke(ctx, "/story.Story/CreateStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) UpdateStories(ctx context.Context, in *UpdateStoriesReq, opts ...grpc.CallOption) (*UpdateStoriesRes, error) {
	out := new(UpdateStoriesRes)
	err := c.cc.Invoke(ctx, "/story.Story/UpdateStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) DeleteStories(ctx context.Context, in *StoryId, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/story.Story/DeleteStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) GetAllStories(ctx context.Context, in *GetAllStoriesReq, opts ...grpc.CallOption) (*GetAllStoriesRes, error) {
	out := new(GetAllStoriesRes)
	err := c.cc.Invoke(ctx, "/story.Story/GetAllStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) GetStory(ctx context.Context, in *StoryId, opts ...grpc.CallOption) (*GetStoryRes, error) {
	out := new(GetStoryRes)
	err := c.cc.Invoke(ctx, "/story.Story/GetStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) CommentStory(ctx context.Context, in *CommentStoryReq, opts ...grpc.CallOption) (*CommentStoryRes, error) {
	out := new(CommentStoryRes)
	err := c.cc.Invoke(ctx, "/story.Story/CommentStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) GetCommentsOfStory(ctx context.Context, in *GetCommentsOfStoryReq, opts ...grpc.CallOption) (*GetCommentsOfStoryRes, error) {
	out := new(GetCommentsOfStoryRes)
	err := c.cc.Invoke(ctx, "/story.Story/GetCommentsOfStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error) {
	out := new(LikeRes)
	err := c.cc.Invoke(ctx, "/story.Story/Like", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServer is the server API for Story service.
// All implementations must embed UnimplementedStoryServer
// for forward compatibility
type StoryServer interface {
	CreateStories(context.Context, *CreateStoriesRequest) (*CreateStoriesResponse, error)
	UpdateStories(context.Context, *UpdateStoriesReq) (*UpdateStoriesRes, error)
	DeleteStories(context.Context, *StoryId) (*Void, error)
	GetAllStories(context.Context, *GetAllStoriesReq) (*GetAllStoriesRes, error)
	GetStory(context.Context, *StoryId) (*GetStoryRes, error)
	CommentStory(context.Context, *CommentStoryReq) (*CommentStoryRes, error)
	GetCommentsOfStory(context.Context, *GetCommentsOfStoryReq) (*GetCommentsOfStoryRes, error)
	Like(context.Context, *LikeReq) (*LikeRes, error)
	mustEmbedUnimplementedStoryServer()
}

// UnimplementedStoryServer must be embedded to have forward compatible implementations.
type UnimplementedStoryServer struct {
}

func (UnimplementedStoryServer) CreateStories(context.Context, *CreateStoriesRequest) (*CreateStoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStories not implemented")
}
func (UnimplementedStoryServer) UpdateStories(context.Context, *UpdateStoriesReq) (*UpdateStoriesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStories not implemented")
}
func (UnimplementedStoryServer) DeleteStories(context.Context, *StoryId) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStories not implemented")
}
func (UnimplementedStoryServer) GetAllStories(context.Context, *GetAllStoriesReq) (*GetAllStoriesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStories not implemented")
}
func (UnimplementedStoryServer) GetStory(context.Context, *StoryId) (*GetStoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStory not implemented")
}
func (UnimplementedStoryServer) CommentStory(context.Context, *CommentStoryReq) (*CommentStoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentStory not implemented")
}
func (UnimplementedStoryServer) GetCommentsOfStory(context.Context, *GetCommentsOfStoryReq) (*GetCommentsOfStoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsOfStory not implemented")
}
func (UnimplementedStoryServer) Like(context.Context, *LikeReq) (*LikeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedStoryServer) mustEmbedUnimplementedStoryServer() {}

// UnsafeStoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoryServer will
// result in compilation errors.
type UnsafeStoryServer interface {
	mustEmbedUnimplementedStoryServer()
}

func RegisterStoryServer(s grpc.ServiceRegistrar, srv StoryServer) {
	s.RegisterService(&Story_ServiceDesc, srv)
}

func _Story_CreateStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).CreateStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/CreateStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).CreateStories(ctx, req.(*CreateStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_UpdateStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).UpdateStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/UpdateStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).UpdateStories(ctx, req.(*UpdateStoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_DeleteStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).DeleteStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/DeleteStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).DeleteStories(ctx, req.(*StoryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_GetAllStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).GetAllStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/GetAllStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).GetAllStories(ctx, req.(*GetAllStoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_GetStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).GetStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/GetStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).GetStory(ctx, req.(*StoryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_CommentStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentStoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).CommentStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/CommentStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).CommentStory(ctx, req.(*CommentStoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_GetCommentsOfStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsOfStoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).GetCommentsOfStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/GetCommentsOfStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).GetCommentsOfStory(ctx, req.(*GetCommentsOfStoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/story.Story/Like",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Story_ServiceDesc is the grpc.ServiceDesc for Story service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Story_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "story.Story",
	HandlerType: (*StoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStories",
			Handler:    _Story_CreateStories_Handler,
		},
		{
			MethodName: "UpdateStories",
			Handler:    _Story_UpdateStories_Handler,
		},
		{
			MethodName: "DeleteStories",
			Handler:    _Story_DeleteStories_Handler,
		},
		{
			MethodName: "GetAllStories",
			Handler:    _Story_GetAllStories_Handler,
		},
		{
			MethodName: "GetStory",
			Handler:    _Story_GetStory_Handler,
		},
		{
			MethodName: "CommentStory",
			Handler:    _Story_CommentStory_Handler,
		},
		{
			MethodName: "GetCommentsOfStory",
			Handler:    _Story_GetCommentsOfStory_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _Story_Like_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stories.proto",
}
